#!/usr/bin/env bash
# configures Nginx server to redirect

sudo apt-get update -y
sudo apt-get -y install nginx

sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /var/www/html;
  index index.html;
  location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
  error_page 404 /404.html;
  location=/404.html{
    internal;
  }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
