#!/bin/bash
# configure web-02
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/http {/a\		add_header X-Served-By $HOSTNAME;" /etc/ngnix/ngnix.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service ngnix restart
