#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash
# shellcheck disable=SC2009

bash=$(pgrep -f "bash")

for process in $bash
do
	process_name=$(ps -p "$process" -o comm=)
	echo "$process $process_name"
done
